server:
  port: 9001
  tomcat:
    threads:
      min-spare: 5
      max: 50
    connection-timeout: 2s
    keep-alive-timeout: 15s
  shutdown: graceful

keycloak:
  realm: chat
  auth-server-url: http://localhost:8080
  resource: edge-service
  credentials:
    secret: cT5pq7W3XStcuFVQMhjPbRj57Iqxcu4n

spring:
  application:
    name: api-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  datasource:
    url: jdbc:postgresql://localhost:5432/main_db
    username: user
    password: password
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/chat